version: '3.9'

services:
  web:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
    restart: always
  php-fpm:
    #image: php:8-fpm
    build:
      context: .
    volumes:
      - ./:/var/www/html
    links:
      - mysql
    restart: always
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: stats
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - '3306:3306'
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d